[package]
name = "conduit-ui"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "conduit_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "conduit-ui"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
